# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '00001111-0000-1111-2222-000011112222'

  # Web app name
  webAppName: 'nodejs-cicd-16353'

  # Environment name
  environmentName: 'nodejs-cicd-16353'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
          - script: |
              npm install
            displayName: 'npm install, build and test'
  - stage: Deploy
    displayName: Deploy Stage
    jobs:
      - deployment: VMDeploy
        displayName: Deploy to VM
        environment: 
          name: Ci-cd Test machine
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:   
              steps:
                - task: Bash@3
                  inputs:
                    targetType: 'inline'
                    script: |
                      cd /home/azureuser/mineswepper/
                      git pull
                      npm install
                      pm2 stop all
                      pm2 start index.js
      # - job: deploy
      #   displayName: Deploy 
      #   pool:
      #     vmImage: $(vmImageName)
      #   steps:
      #     - task: InstallSSHKey@0
      #       inputs:
      #         knownHostsEntry: '20.115.92.201'
      #         sshKeySecureFile: 'azure-ssh.pem'
      #     - task: SSH@0
      #       inputs:
      #         sshEndpoint: 'azureuser@20.115.92.201'
      #         commands: mkdir hello

